[database]
db_url = postgresql://user:password@localhost:5432/rootnode

[redis]
redis_url = redis://localhost:6379/0

[celery]
broker_url = redis://localhost:6379/0
result_backend = redis://localhost:6379/0

[docker]
docker_host = unix:///var/run/docker.sock

[app]
port = 8000
admin_port = 8001
host = 0.0.0.0
debug = True
