[database]
db_url = postgresql://019d4d54-235b-7bdc-a112-12ed135ba8b6:a80b923f-64f1-4032-b862-0bd3b99a7d66@us-west-2.db.thenile.dev/nile_blue_grass?sslmode=require

[redis]
redis_url = rediss://default:gQAAAAAAASSqAAIncDJhZTdiNThiZTI4NTg0MzkyYTk2OWEwZjhjOGNhYmNhNHAyNzQ5MjI@charmed-cod-74922.upstash.io:6379

[celery]
broker_url = rediss://default:gQAAAAAAASSqAAIncDJhZTdiNThiZTI4NTg0MzkyYTk2OWEwZjhjOGNhYmNhNHAyNzQ5MjI@charmed-cod-74922.upstash.io:6379
result_backend = rediss://default:gQAAAAAAASSqAAIncDJhZTdiNThiZTI4NTg0MzkyYTk2OWEwZjhjOGNhYmNhNHAyNzQ5MjI@charmed-cod-74922.upstash.io:6379

[docker]
docker_host = unix:///var/run/docker.sock

[app]
port = 8000
admin_port = 8001
host = 0.0.0.0
debug = True

[firebase]
firebase_project_id = rootnode-6c629
firebase_client_email = firebase-adminsdk-fbsvc@rootnode-6c629.iam.gserviceaccount.com
firebase_private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxPTVE6D7wKpB8\nt+zvaAAPy337iJELLYsAIZYFi3KEkSP7qdfxTvgFxDfcczX/ZZTA9AyovLXYlFrb\nhDcuth/vXTkT9D3qVPR6vXJS20ELqKlwopG8UxYNlggl5rncYsLJdVJm4QGh4+KO\nrt5fcXYrf9ZBaxjczKD73AhI3hdsU6HClJXYMAkcx2ZWYaP5Wj2HDFadaZNdNWdr\n3BKdoHy7XOE6+cCCOVdfBW3kUN4n15nj7HcUISxg/RhnEhclLr9qc5F+b2GNoipA\nfwFQ9wz/XepP/Xy9vD/VWbJtG4Vm1av9prj1fRKrOA8e8aEbXU9uaMVKSUXHlEJi\nIXJEH0tBAgMBAAECggEAANhQhno93T16Q8GCDlWxCmI8pGl2RAGZWykGuEuaV7hX\npOhlfrbL43eYA7HuQGrKOlFE3/WCzcNOac5kcy3k4RUKB0pTP3bAOPdblYGKiPUH\nHVOwMp/fObXM9QhpdDTbcOCoiM0HJkw2f9pPWYmU8N17mjw9XTc6wM34oXkxJEjW\n3dBK6l2cjFMOhCJmAsxM62vMyMpWWTD0FwF3dADbfCptERXUMdYalWW+1jYpARo8\nR8V6r0uWju1+JkqGxp+iF0Ck/4eyk1OAcNjcAIxNZgdSaBWV+KPqYdw0XSkEvAUi\nMjfBP73ARbPP4V8vj0OGdNQKKYX2joSB7REWFxaUAQKBgQDaRtWdMOHg/3thC2MK\nj1kbYV8ig2Xxpuez0XPsLHs/9B+BZwr4EJGfhKDHckUWfA/lCVjsb8ZOEd2Mcobr\nlIqsYEJ6apkWefDq2NhXnFb/v4fXkSI24t5VTBiu9puAgA8WRc9SzTBDL8hsYhGV\nQ1BRxg9cTskkmjnlGZe2O7qPkQKBgQDP3sGmuc86joIjFokKae5twU8VZKg02jLM\nCO08ixwwSX9eaFHgY2QBdOOMQvtOpdklMIgPptzPI2IITwczXMctFFTvmxiqMU7A\nwfz/8wKZXAOZms/Bqfse+dfFh/ByY5tBZtt6PA4qPXX8cSsG7HcBvOGzz1XSfYFU\nWKRHuY2IsQKBgQC4iNYjlKYCQDugqa3LybD9su5pEUloaUDOBy/H5Ts1sD/KeMEP\nQ4K5p7j9pR+/iJcvfR2OlljCu9vf1xs1o1kxrhfFwsU1+VWyVi1gtC3g/Z3soyiX\n2mk5F6JumNKSarFWlSJX0F0TEByTdL2EwWnwGE/4LCtlJHX5uA9I42ov4QKBgBXC\nL2sQUAzFFgIuPbIFXJvIfEq0+pZtsJuC47JOrWiwiNCNAuUGAlXUsmzgJgYZfh1S\ncyuQP9S+02gjPZG2yHKDilB6X56RArlSlPUFruP2qbnOZqjS7iJT7K4UiKqwmnPC\nHH8zAhiRzmPaRLK41cwsxUNZFJav5HW7wZZwacxBAoGAD58+raMvJ/8KAhlEdxPi\nortg7eYOhMwVnxwSI2OGi4FSVG2rDIrZ6Ous25W00ywBRx8SmjM0UquSgyJ0GMwj\nHDhl+CKcvP2K0JnetoDl5QIElkVwppQET9f8XlhIBpivK3yZO52KgGqmWBIkk0dN\nO21RwZmYuUxrHKdwhjuPQTI=\n-----END PRIVATE KEY-----\n"
